#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_

/* Options for EXTI0_MODE :
 - EXTI0_MODE_LOW_LEVEL				- EXTI0_MODE_ANY_LOGICAL_CHANGE
 - EXTI0_MODE_FALLING				- EXTI0_MODE_RISING
 */
#define EXTI0_MODE  	EXTI0_MODE_FALLING

/* Options for EXTI0_MODE :
 - EXTI1_MODE_LOW_LEVEL				- EXTI1_MODE_ANY_LOGICAL_CHANGE
 - EXTI1_MODE_FALLING				- EXTI1_MODE_RISING
 */
#define EXTI1_MODE 		EXTI1_MODE_FALLING

/* Options for EXTI2_MODE:
 - EXTI2_MODE_RISING					- EXTI2_MODE_FALLING 
 */
#define EXTI2_MODE 		EXTI2_MODE_FALLING	

#endif